### ISSUE TITLE
有个小疑问

### ISSUE THREAD

**Issue by czy0729** [lij963/wx-mini-program-sortable-gridview#1]
https://github.com/lij963/wx-mini-program-sortable-gridview/blob/1bf5f7729297465c45a5cc9aae0a91444039a09c/pages/sort/sort.js#L222

data不是对象吗, 那这个永远都是true, 一直都会setData

**Comment by lij963** [comment]
空对象是false

**Comment by czy0729** [comment]
小程序的空对象不是跟JS的空对象一样是true? 
思路我全抄过来了, 很好用, 谢谢

https://upload.cc/i1/2019/09/21/zOGP17.gif
